# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linterest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Meal', 'Meal'), ('Movie', 'Movie'), ('Drink', 'Drink'), ('Party', 'Party')], default='meal', max_length=30)),
                ('city', models.CharField(default='Pittsburgh', max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
