# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linterest', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(related_name='following_event', to='linterest.Profile'),
        ),
    ]
