# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linterest', '0003_auto_20161127_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
