# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linterest', '0004_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to='linterest.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member', to='linterest.Profile'),
        ),
    ]
