# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linterest', '0009_auto_20161204_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, default=4120000000),
        ),
    ]
